### ISSUE TITLE
Missing default jdbc.connections.* Spring Boot metrics

### ISSUE THREAD

**Issue by stefano-salmaso** [jdbc-observations/datasource-micrometer#46] opened 2024-08-30 08:10 UTC
Hi all,
using Spring Boot you have metrics about connections like
```
jdbc.connections.min
jdbc.connections.max
jdbc.connections.idle
jdbc.connections.active
```
When tracing is enabled we are creating a `ProxyDataSourceBuilderCustomizer` to have tracing info.
Doing this we have the new metrics (jdbc.conection, jdbc.query, jdbc.result-set ...) but the metrics created by Spring Boot disappears!

Is there a way to get previous metrics as well when using datasource-micrometer?

Thanks

**Comment by ttddyy** [comment] 2024-08-30 23:41
Hi @stefano-salmaso 

Looking at the Spring Boot code, `DataSourcePoolMetricsAutoConfiguration` seems to be the one that registers the `DataSourcePoolMetrics` binder.
Specifically [here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/jdbc/DataSourcePoolMetricsAutoConfiguration.java#L94-L99).

I don't see it would interfere with `DataSourceObservationBeanPostProcessor` which creates a proxy from datasource-micrometer.

Can you try to debug the behavior on the `DataSourcePoolMetricsAutoConfiguration` on your app to see whether it is registering the binders correctly??

**Comment by stefano-salmaso** [comment] 2024-09-02 07:32
Hi @ttddyy 
I think the problem is related to the fact you are using a proxy.
[Here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/jdbc/DataSourcePoolMetrics.java#L68)  the `metadataProvider`return null passing the proxy... but return the value using real datasource.
Going deeper.. [here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/metadata/DataSourcePoolMetadataProvidersConfiguration.java#L55) the function `DataSourceUnwrapper.unwrap` is not able to return the datasource. This method tries in multiple way to obtain the datasource... but with `ProxyDataSource` it seems not working...

**Comment by stefano-salmaso** [comment] 2024-09-02 13:25
I found a workaround... adding this implementation of `DataSourcePoolMetadataProvider` as a Bean solve the issue
```
    @Bean
    DataSourcePoolMetadataProvider proxyDatasourceTomcatPoolDataSourceMetadataProvider() {
        return dataSource -> {
            if(dataSource instanceof ProxyDataSource) {
                org.apache.tomcat.jdbc.pool.DataSource tomcatDataSource = DataSourceUnwrapper.unwrap(((ProxyDataSource) dataSource).getDataSource(), ConnectionPoolMBean.class, org.apache.tomcat.jdbc.pool.DataSource.class);
                return tomcatDataSource != null ? new TomcatDataSourcePoolMetadata(tomcatDataSource) : null;
            }
            return null;
        };
    }
```
I didn't check if we have issue Hikari CP and, also, this implementation needs `org.apache.tomcat:tomcat-jdbc` dependency

**Comment by ttddyy** [comment] 2024-11-03 01:32
After more digging, it's a bug in `tomcat-jdbc`.

The `org.apache.tomcat.jdbc.pool.DataSource` always returns `false` for `isWrapperFor` and `null` for `unwrap` methods: https://github.com/apache/tomcat/blob/main/modules/jdbc-pool/src/main/java/org/apache/tomcat/jdbc/pool/DataSourceProxy.java#L62-L73

I see there is a bug filed in 2016 but I don't see it has anything addressed.
https://bz.apache.org/bugzilla/show_bug.cgi?id=59569


The reason why `DataSourceUnwrapper.unwrap` on `org.apache.tomcat.jdbc.pool.DataSource` works is that it checks the instance itself:
https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jdbc/DataSourceUnwrapper.java#L57-L59
So, essentially, it does `datasource instanceof ConnectionPoolMBean`, which returns `true` and returns the tomcat datasource.
However, in this case, it should also return `true` for `datasource.isWrapperFor(ConnectionPoolMBean.class)`, yet it returns `false`.

I think the suggested workaround in [the above comment](https://github.com/jdbc-observations/datasource-micrometer/issues/46#issuecomment-2324757900) is a good approach for now.

Since the root cause is in `tomcat-jdbc` and cannot be resolved by `datasource-proxy` or `datasource-micrometer`, I am closing this issue.

**Closed by ttddyy** 2024-11-03 01:32 UTC
